// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"Chimaki_EventPlus","status":true,"description":"影子事件設定","parameters":{}},
{"name":"Chimaki_WaitMessage","status":true,"description":"map資訊","parameters":{"boss_window":"0;0;300;200;left;0","fontSize":"32","fadeSpeed":"10;30","timer_window":"0;200;300;100;left;1","timerFontSize":"32","timerFadeSpeed":"10;30\r"}}
];
